Move zeroes
ranaSalamehTesting/MediumQuestions pull request #4
Opened 2023-04-25 20:58 UTC by ranaSalamehTesting

2023-05-05 02:57 UTC, hayatzsala requested changes

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Move.cs
> +    public class Move
again, class name is always noun not Verb

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Program.cs
> +    class Program : Move
Why Program class inherits Move class !??

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Move.cs
> +        internal void Print(int[] numbers)
let's be more consistent, either all methods and class public or internal

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Move.cs
> +            }
Read about string.join and try to use it here instead of the loop

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Move.cs
> +        }
please add an access modifier for this method

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Move.cs
> +                }
actually, I don't see the order of non-zeros numbers.

2023-05-05 02:57 UTC, hayatzsala commented on Move-Zeros/Move.cs
> +namespace Move_Zeros
NOT recommended to use special characters in namespace ,project, solution name

2023-05-07 19:12 UTC, ranaSalamehTesting commented on Move-Zeros/Program.cs
> +    class Program : Move
by mistake

2023-05-07 19:29 UTC, merged